
osc=no
border=yes

vo=gpu-next
hwdec=auto
gpu-api=d3d11
video-sync=display-resample

cache=yes
demuxer-max-bytes=256MiB
demuxer-max-back-bytes=64MiB

# 不启动 hq，使用比较经典的缩放算法：
scale=spline36
cscale=bilinear
dscale=mitchell
deband=no

# 音量均衡
#audio-normalize=yes

# 播放速度
# 屏幕旋转
loop-file=inf

# 限制窗口始终小于屏幕 
autofit-larger=90%x90%
# 禁止拖动画面时触发窗口拖动
input-builtin-dragging=no
window-dragging=no
# 缩放变小时，自动居中
video-recenter=yes

# autoload
autocreate-playlist=same

# Plugins:
# https://github.com/tsl0922/mpv-menu-plugin: dyn_menu.lua, menu.dll, dialog.lua
# pause-when-minimize.lua
