
osc=no
border=no

border=no

vo=gpu-next
hwdec=auto
gpu-api=d3d11

cache=yes
demuxer-max-bytes=256MiB
demuxer-max-back-bytes=64MiB

# 高质量缩放
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp

# 音量均衡
#audio-normalize=yes

# 播放速度
# 屏幕旋转
#
loop-file=inf
